### ISSUE TITLE
 java.lang.NoClassDefFoundError: com/google/zxing/LuminanceSource

### ISSUE THREAD

**Issue by coolstar1204** [ariesliu/QRcode4JAVA#1]
你的二维码生成jar,有报这个错误
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/zxing/LuminanceSource
        at com.qihoo.test.QRcodeTest.main(QRcodeTest.java:32)
Caused by: java.lang.ClassNotFoundException: com.google.zxing.LuminanceSource
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

**Comment by ariesliu** [comment]
启动的命令行是什么？方便贴一下吗？

**Comment by bingshushu** [comment]
怎么不把编译好的jar放出来，我自己编译的也是这个错误。而且已经把zxing包放进去了

**Comment by bingshushu** [comment]
把zxing的源码拷出来重新编译，可以运行了。。

**Comment by arsenalpoll** [comment]
什么时候上传一个完整的jar啊 编译报错的

**Comment by ariesliu** [comment]
已经上传了一个编译成功的jar包成品，试用一下看看
